const {PrismaClient} = require("@prisma/client")

const prisma = new PrismaClient;

const medicines = [
  {
    name: "Paracetamol 500 mg",
    categoryId: 1,
    price: 5000,
    stock: 120,
    drug_class: "Obat_Bebas",
    indication: "Meredakan nyeri dan menurunkan demam",
    dosage: "3–4 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mual ringan",
  },
  {
    name: "Ibuprofen 400 mg",
    categoryId: 1,
    price: 8000,
    stock: 90,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Nyeri dan peradangan",
    dosage: "3 kali sehari 1 tablet",
    min_age: 12,
    side_effect: "Iritasi lambung",
  },
  {
    name: "Asam Mefenamat 500 mg",
    categoryId: 1,
    price: 7000,
    stock: 75,
    drug_class: "Obat_keras",
    indication: "Nyeri sedang hingga berat",
    dosage: "3 kali sehari 1 kapsul",
    min_age: 14,
    side_effect: "Nyeri lambung",
  },
  {
    name: "Amoxicillin 500 mg",
    categoryId: 2,
    price: 12000,
    stock: 80,
    drug_class: "Obat_keras",
    indication: "Infeksi bakteri",
    dosage: "3 kali sehari 1 kapsul",
    min_age: 12,
    side_effect: "Diare, ruam",
  },
  {
    name: "Ciprofloxacin 500 mg",
    categoryId: 2,
    price: 18000,
    stock: 60,
    drug_class: "Obat_keras",
    indication: "Infeksi bakteri berat",
    dosage: "2 kali sehari 1 tablet",
    min_age: 18,
    side_effect: "Mual, pusing",
  },
  {
    name: "Cefixime 100 mg",
    categoryId: 2,
    price: 15000,
    stock: 70,
    drug_class: "Obat_keras",
    indication: "Infeksi saluran pernapasan",
    dosage: "2 kali sehari 1 kapsul",
    min_age: 6,
    side_effect: "Diare",
  },
  {
    name: "CTM",
    categoryId: 3,
    price: 3000,
    stock: 200,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Alergi, gatal, bersin",
    dosage: "2–3 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mengantuk",
  },
  {
    name: "Loratadine 10 mg",
    categoryId: 3,
    price: 9000,
    stock: 100,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Rinitis alergi",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Sakit kepala",
  },
  {
    name: "Cetirizine 10 mg",
    categoryId: 3,
    price: 8500,
    stock: 110,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Alergi dan biduran",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mengantuk ringan",
  },
  {
    name: "OBH Sirup",
    categoryId: 4,
    price: 15000,
    stock: 60,
    drug_class: "Obat_Bebas",
    indication: "Batuk berdahak",
    dosage: "3 kali sehari 1 sendok takar",
    min_age: 2,
    side_effect: "Mual ringan",
  },
  {
    name: "Decolgen",
    categoryId: 4,
    price: 6000,
    stock: 130,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Flu dan hidung tersumbat",
    dosage: "3 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mengantuk",
  },
  {
    name: "Mixagrip",
    categoryId: 4,
    price: 6500,
    stock: 140,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Flu, demam, sakit kepala",
    dosage: "3 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mengantuk",
  },
  {
    name: "Antasida DOEN",
    categoryId: 5,
    price: 7000,
    stock: 90,
    drug_class: "Obat_Bebas",
    indication: "Maag dan nyeri ulu hati",
    dosage: "3–4 kali sehari 1–2 tablet",
    min_age: 12,
    side_effect: "Sembelit",
  },
  {
    name: "Omeprazole 20 mg",
    categoryId: 5,
    price: 14000,
    stock: 65,
    drug_class: "Obat_keras",
    indication: "GERD dan tukak lambung",
    dosage: "1 kali sehari 1 kapsul",
    min_age: 18,
    side_effect: "Sakit kepala",
  },
  {
    name: "Loperamide",
    categoryId: 5,
    price: 5000,
    stock: 100,
    drug_class: "Obat_Bebas_Terbatas",
    indication: "Diare akut",
    dosage: "Setelah diare 1 kapsul",
    min_age: 6,
    side_effect: "Sembelit",
  },
  {
    name: "Vitamin C 500 mg",
    categoryId: 6,
    price: 10000,
    stock: 150,
    drug_class: "Obat_Bebas",
    indication: "Menjaga daya tahan tubuh",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Iritasi lambung",
  },
  {
    name: "Vitamin B Complex",
    categoryId: 6,
    price: 9000,
    stock: 160,
    drug_class: "Obat_Bebas",
    indication: "Menjaga fungsi saraf",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mual ringan",
  },
  {
    name: "Vitamin D3",
    categoryId: 6,
    price: 12000,
    stock: 110,
    drug_class: "Obat_Bebas",
    indication: "Kesehatan tulang",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: null,
  },
  {
    name: "Zinc 20 mg",
    categoryId: 6,
    price: 11000,
    stock: 95,
    drug_class: "Obat_Bebas",
    indication: "Mendukung sistem imun",
    dosage: "1 kali sehari 1 tablet",
    min_age: 6,
    side_effect: "Mual",
  },
  {
    name: "Multivitamin Anak",
    categoryId: 6,
    price: 13000,
    stock: 85,
    drug_class: "Obat_Bebas",
    indication: "Mendukung pertumbuhan anak",
    dosage: "1 kali sehari 1 tablet kunyah",
    min_age: 4,
    side_effect: null,
  },
];

module.exports = { medicines };



const main= async()=>{
    console.log("seeding...")
    for (const medicine of medicines){
        await prisma.medicine.create({
            data: medicine,
        })
        console.log("created category", medicine)
    }
    console.log("seeding complete")
}
main().catch((err) =>{
    console.error(err)
    process.exit(1)

}).finally(async()=>{
    await prisma.$disconnect
})